# Generated by Django 6.0.5 on 2026-05-28 14:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('texto', models.TextField()),
                ('cargo_ou_relacao', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('evento', 'Evento'), ('campanha', 'Campanha'), ('acao_social', 'Acao social')], default='evento', max_length=20)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=180)),
                ('imagem', models.ImageField(blank=True, upload_to='eventos/')),
                ('meta_arrecadacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evento ou campanha',
                'verbose_name_plural': 'eventos e campanhas',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='ACITP', max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True)),
                ('endereco', models.CharField(default='Estrada do Babi, 14455, Vila Magalhaes em Belford Roxo', max_length=255)),
                ('telefone', models.CharField(default='(+55) 21 96441-4945', max_length=30)),
                ('email', models.EmailField(default='acitp2010@gmail.com', max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('chave_pix', models.CharField(default='acitp2010@gmail.com', max_length=120)),
                ('formas_doacao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'instituicao',
                'verbose_name_plural': 'instituicoes',
            },
        ),
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('assunto', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('respondida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mensagem de contato',
                'verbose_name_plural': 'mensagens de contato',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='PrestacaoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('resumo', models.TextField()),
                ('valor_arrecadado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_utilizado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arquivo', models.FileField(blank=True, upload_to='prestacoes/')),
                ('publicado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'prestacao de conta',
                'verbose_name_plural': 'prestacoes de contas',
                'ordering': ['-periodo_fim'],
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=30)),
                ('profissao', models.CharField(blank=True, max_length=120)),
                ('motivacao', models.TextField(blank=True)),
                ('disponibilidade', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em analise'), ('aprovado', 'Aprovado'), ('inativo', 'Inativo')], default='novo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'voluntario',
                'verbose_name_plural': 'voluntarios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doador_nome', models.CharField(blank=True, max_length=150)),
                ('doador_email', models.EmailField(blank=True, max_length=254)),
                ('doador_telefone', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('item', 'Item'), ('alimento', 'Alimento'), ('medicamento', 'Medicamento'), ('outro', 'Outro')], default='dinheiro', max_length=20)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_doado', models.CharField(blank=True, max_length=150)),
                ('quantidade', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doacao',
                'verbose_name_plural': 'doacoes',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
